NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-mit-bme-hu-7010.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-mit-bme-hu-7010.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-mit-bme-hu-7010.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-mit-bme-hu-7010.pem
    OrganizationalUnitIdentifier: orderer
