NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-tmit-bme-hu-7110.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-tmit-bme-hu-7110.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-tmit-bme-hu-7110.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-tmit-bme-hu-7110.pem
    OrganizationalUnitIdentifier: orderer
